id: IEABF449E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T07:18:45+00:00'
last_modified: '2022-06-08T04:34:30.650906+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W293
  title: སྙན་ངག་གི་བསྟན་བཅོས་མེ་ལོང་གི་རྩ་བ་དང་འགྲེལ་པ་དབྱངས་ཅན་དགྱེས་པའི་གླུ་དབྱངས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4AAF:
      image_group_id: I1KG10667
      title: ''
      total_pages: 352
      order: 1
      base_file: 4AAF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
